#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const resourcesDir = path.join(__dirname, '..', 'public', 'Resources');
const sourcePath = path.join(resourcesDir, 'library.json');
const targetPath = path.join(resourcesDir, 'library-embedded.js');

function main() {
    if (!fs.existsSync(sourcePath)) {
        throw new Error('Unable to find public/Resources/library.json to sync.');
    }
    const raw = fs.readFileSync(sourcePath, 'utf8');
    let data;
    try {
        data = JSON.parse(raw);
    } catch (err) {
        throw new Error(`library.json contains invalid JSON: ${err.message}`);
    }
    const serialized = JSON.stringify(data, null, 2);
    const banner = '// Auto-generated by scripts/sync-library.js. Do not edit manually.\n';
    const content = `${banner}window.__uploadedLifeEmbeddedLibrary = ${serialized};\n`;
    fs.writeFileSync(targetPath, content, 'utf8');
    console.log(`Synced ${sourcePath} -> ${targetPath}`);
}

main();
